import { StyleSheet } from 'react-native';
import { colors, spacing } from '../../common/theme';

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: colors.ivory4,
		padding: spacing.medium,
	},
	title: {
		fontSize: 18,
		fontWeight: '700',
		color: colors.orangeShade7,
		marginBottom: spacing.small,
	},
	sectionTitle: {
		fontSize: 16,
		fontWeight: '700',
		color: colors.orangeShade6,
		marginTop: spacing.medium,
		marginBottom: spacing.small,
	},
	kmRow: {
		flexDirection: 'row',
		alignItems: 'center',
		marginBottom: spacing.small,
	},
	// Tab styles
	tabContainer: {
		flexDirection: 'row',
		backgroundColor: colors.ivory1,
		borderRadius: 12,
		padding: 4,
		marginBottom: spacing.medium,
		borderWidth: 1,
		borderColor: colors.ivory3,
	},
	tab: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: 10,
		paddingHorizontal: 12,
		borderRadius: 10,
		gap: 6,
	},
	tabActive: {
		backgroundColor: colors.primary + '15',
	},
	tabText: {
		fontSize: 13,
		fontWeight: '600',
		color: colors.orangeShade5,
	},
	tabTextActive: {
		color: colors.primary,
	},
	kmInput: {
		flex: 1,
		backgroundColor: colors.ivory1,
		padding: spacing.small,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: colors.ivory3,
	},
	saveBtn: {
		marginLeft: spacing.small,
		backgroundColor: colors.primary,
		paddingVertical: 8,
		paddingHorizontal: 12,
		borderRadius: 8,
		flexDirection: 'row',
		alignItems: 'center',
	},
	saveText: {
		color: colors.ivory1,
		marginLeft: 6,
		fontWeight: '600',
	},
	group: {
		marginTop: spacing.medium,
	},
	groupHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: spacing.small,
	},
	groupTitle: {
		fontSize: 14,
		fontWeight: '700',
		color: colors.orangeShade6,
		flex: 1,
	},
	reminderBadge: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: colors.primary + '15',
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 12,
		gap: 4,
	},
	reminderBadgeText: {
		fontSize: 11,
		fontWeight: '600',
		color: colors.primary,
	},
	card: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: colors.ivory1,
		padding: spacing.small,
		borderRadius: 10,
		marginBottom: spacing.small,
		borderWidth: 1,
		borderColor: colors.ivory3,
		position: 'relative',
	},
	statusIndicator: {
		width: 4,
		height: '100%',
		position: 'absolute',
		left: 0,
		top: 0,
		borderTopLeftRadius: 10,
		borderBottomLeftRadius: 10,
	},
	cardLeft: { flex: 1, paddingLeft: 8 },
	cardRight: {
		marginLeft: spacing.small,
		alignItems: 'center',
	},
	itemName: { fontWeight: '700', color: colors.orangeShade7 },
	itemNotes: { fontSize: 12, color: colors.orangeShade5, marginBottom: 6 },
	small: { fontSize: 11, color: colors.orangeShade5 },
	timeInfoRow: {
		marginTop: 2,
	},
	progressSection: {
		flexDirection: 'row',
		alignItems: 'center',
		marginTop: 6,
		gap: 6,
	},
	progressLabel: {
		fontSize: 10,
		fontWeight: '600',
		color: colors.orangeShade5,
		width: 30,
	},
	barBackgroundSmall: {
		flex: 1,
		height: 6,
		backgroundColor: '#eee',
		borderRadius: 4,
		overflow: 'hidden',
	},
	barFillSmall: {
		height: 6,
	},
	progressPercent: {
		fontSize: 10,
		fontWeight: '600',
		width: 32,
		textAlign: 'right',
	},
	statusText: {
		fontSize: 11,
		fontWeight: '700',
		marginTop: 6,
	},
	barBackground: {
		height: 8,
		backgroundColor: '#eee',
		borderRadius: 6,
		overflow: 'hidden',
		marginTop: spacing.small,
		marginBottom: spacing.xsmall,
	},
	barFill: {
		height: 8,
		backgroundColor: colors.primary,
	},
	doneBtn: {
		backgroundColor: '#28a745',
		padding: 8,
		borderRadius: 8,
		marginBottom: 6,
	},
	deferBtn: {
		backgroundColor: colors.ivory2,
		padding: 8,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: colors.ivory3,
	},
	deferredReasonBox: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#FEF3C7',
		padding: 6,
		borderRadius: 6,
		marginTop: 6,
		gap: 4,
	},
	deferredReasonText: {
		fontSize: 10,
		color: '#92400E',
		flex: 1,
	},
	deferredDateText: {
		fontSize: 9,
		color: '#B45309',
	},
	odometerRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		backgroundColor: colors.ivory1,
		padding: spacing.small,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: colors.ivory3,
		marginBottom: spacing.medium,
	},
	odometerLabel: {
		fontSize: 14,
		fontWeight: '500',
		color: colors.orangeShade6,
	},
	odometerValue: {
		fontSize: 16,
		fontWeight: '700',
		color: colors.orangeShade7,
	},
	alertBanner: {
		flexDirection: 'row',
		alignItems: 'center',
		padding: spacing.small,
		borderRadius: 8,
		marginBottom: spacing.medium,
	},
	criticalBanner: {
		backgroundColor: '#DC2626',
	},
	wornBanner: {
		backgroundColor: '#F59E0B',
	},
	alertText: {
		flex: 1,
		color: '#FFF',
		fontSize: 13,
		fontWeight: '600',
		marginLeft: 8,
	},
	alertButton: {
		padding: 8,
		backgroundColor: 'rgba(255,255,255,0.2)',
		borderRadius: 6,
	},
	// Modal styles
	modalOverlay: {
		flex: 1,
		backgroundColor: 'rgba(0,0,0,0.5)',
		justifyContent: 'center',
		alignItems: 'center',
		padding: spacing.medium,
	},
	overdueModal: {
		backgroundColor: colors.ivory1,
		borderRadius: 16,
		padding: spacing.large,
		width: '100%',
		maxHeight: '85%',
	},
	overdueModalHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		marginBottom: spacing.small,
		gap: 10,
	},
	overdueModalTitle: {
		fontSize: 18,
		fontWeight: '700',
		color: '#DC2626',
		flex: 1,
	},
	overdueModalSubtitle: {
		fontSize: 13,
		color: colors.orangeShade5,
		marginBottom: spacing.medium,
		lineHeight: 18,
	},
	overdueList: {
		maxHeight: 400,
	},
	overdueItem: {
		backgroundColor: colors.ivory2,
		borderRadius: 12,
		padding: spacing.medium,
		marginBottom: spacing.small,
		borderWidth: 1,
		borderColor: '#FCA5A5',
	},
	overdueItemHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: 4,
	},
	overdueItemName: {
		fontSize: 15,
		fontWeight: '700',
		color: colors.orangeShade7,
		flex: 1,
	},
	overdueBadge: {
		backgroundColor: '#FEE2E2',
		paddingHorizontal: 8,
		paddingVertical: 2,
		borderRadius: 10,
	},
	overdueBadgeText: {
		fontSize: 10,
		fontWeight: '600',
		color: '#DC2626',
	},
	overdueItemNotes: {
		fontSize: 12,
		color: colors.orangeShade5,
		marginBottom: 8,
	},
	overdueStats: {
		flexDirection: 'row',
		gap: 12,
		marginBottom: 10,
	},
	overdueStatText: {
		fontSize: 11,
		color: '#DC2626',
		fontWeight: '600',
	},
	overdueActions: {
		flexDirection: 'row',
		gap: 10,
	},
	completeBtn: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#22C55E',
		paddingVertical: 10,
		borderRadius: 8,
		gap: 6,
	},
	completeBtnText: {
		color: '#FFF',
		fontWeight: '600',
		fontSize: 13,
	},
	skipBtn: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.ivory1,
		paddingVertical: 10,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: colors.primary,
		gap: 6,
	},
	skipBtnText: {
		color: colors.primary,
		fontWeight: '600',
		fontSize: 13,
	},
	modalCloseBtn: {
		backgroundColor: colors.primary,
		paddingVertical: 12,
		borderRadius: 8,
		alignItems: 'center',
		marginTop: spacing.medium,
	},
	modalCloseBtnText: {
		color: '#FFF',
		fontWeight: '600',
		fontSize: 14,
	},
	// Skip Modal styles
	skipModal: {
		backgroundColor: colors.ivory1,
		borderRadius: 16,
		padding: spacing.large,
		width: '100%',
		maxHeight: '80%',
	},
	skipModalHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		marginBottom: spacing.medium,
		gap: 10,
	},
	skipModalTitle: {
		fontSize: 16,
		fontWeight: '700',
		color: colors.orangeShade7,
		flex: 1,
	},
	skipItemInfo: {
		backgroundColor: colors.ivory2,
		padding: spacing.small,
		borderRadius: 8,
		marginBottom: spacing.medium,
	},
	skipItemName: {
		fontSize: 14,
		fontWeight: '700',
		color: colors.orangeShade7,
	},
	skipItemOverdue: {
		fontSize: 12,
		color: '#DC2626',
		marginTop: 2,
	},
	skipReasonLabel: {
		fontSize: 13,
		fontWeight: '600',
		color: colors.orangeShade6,
		marginBottom: spacing.small,
	},
	skipReasonList: {
		maxHeight: 220,
	},
	skipReasonOption: {
		flexDirection: 'row',
		alignItems: 'center',
		padding: spacing.small,
		backgroundColor: colors.ivory2,
		borderRadius: 8,
		marginBottom: 8,
		gap: 10,
		borderWidth: 1,
		borderColor: colors.ivory3,
	},
	skipReasonOptionSelected: {
		backgroundColor: colors.primary + '10',
		borderColor: colors.primary,
	},
	skipReasonOptionText: {
		flex: 1,
		fontSize: 14,
		color: colors.orangeShade6,
	},
	skipReasonOptionTextSelected: {
		color: colors.primary,
		fontWeight: '600',
	},
	customReasonInput: {
		backgroundColor: colors.ivory2,
		borderRadius: 8,
		padding: spacing.small,
		borderWidth: 1,
		borderColor: colors.ivory3,
		marginTop: spacing.small,
		fontSize: 14,
		color: colors.orangeShade7,
		minHeight: 80,
		textAlignVertical: 'top',
	},
	skipModalActions: {
		flexDirection: 'row',
		gap: 10,
		marginTop: spacing.medium,
	},
	skipCancelBtn: {
		flex: 1,
		paddingVertical: 12,
		borderRadius: 8,
		alignItems: 'center',
		backgroundColor: colors.ivory2,
		borderWidth: 1,
		borderColor: colors.ivory3,
	},
	skipCancelBtnText: {
		color: colors.orangeShade6,
		fontWeight: '600',
		fontSize: 14,
	},
	skipSubmitBtn: {
		flex: 1,
		paddingVertical: 12,
		borderRadius: 8,
		alignItems: 'center',
		backgroundColor: colors.primary,
	},
	skipSubmitBtnDisabled: {
		backgroundColor: colors.orangeShade3,
	},
	skipSubmitBtnText: {
		color: '#FFF',
		fontWeight: '600',
		fontSize: 14,
	},
	// Completion Modal styles
	completionModalScroll: {
		flexGrow: 1,
		justifyContent: 'center',
		padding: spacing.medium,
	},
	completionModal: {
		backgroundColor: colors.ivory1,
		borderRadius: 16,
		padding: spacing.large,
		width: '100%',
	},
	completionModalHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		marginBottom: spacing.medium,
		gap: 10,
	},
	completionModalTitle: {
		fontSize: 18,
		fontWeight: '700',
		color: '#22C55E',
		flex: 1,
	},
	completionItemInfo: {
		backgroundColor: colors.ivory2,
		padding: spacing.medium,
		borderRadius: 10,
		marginBottom: spacing.medium,
		borderLeftWidth: 4,
		borderLeftColor: '#22C55E',
	},
	completionItemName: {
		fontSize: 16,
		fontWeight: '700',
		color: colors.orangeShade7,
	},
	completionItemGroup: {
		fontSize: 12,
		color: colors.primary,
		marginTop: 2,
	},
	completionItemNotes: {
		fontSize: 12,
		color: colors.orangeShade5,
		marginTop: 4,
		fontStyle: 'italic',
	},
	currentReadingsBox: {
		backgroundColor: '#F0FDF4',
		padding: spacing.small,
		borderRadius: 8,
		marginBottom: spacing.medium,
		borderWidth: 1,
		borderColor: '#BBF7D0',
	},
	readingRow: {
		flexDirection: 'row',
		alignItems: 'center',
		marginBottom: 6,
		gap: 8,
	},
	readingLabel: {
		fontSize: 12,
		color: colors.orangeShade5,
		flex: 1,
	},
	readingValue: {
		fontSize: 12,
		fontWeight: '600',
		color: colors.orangeShade7,
	},
	completionLabel: {
		fontSize: 13,
		fontWeight: '600',
		color: colors.orangeShade6,
		marginBottom: 8,
		marginTop: spacing.small,
	},
	statusOptionsRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
		marginBottom: spacing.small,
	},
	statusOption: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 12,
		paddingVertical: 8,
		backgroundColor: colors.ivory2,
		borderRadius: 20,
		borderWidth: 1,
		borderColor: colors.ivory3,
		gap: 6,
	},
	statusOptionSelected: {
		backgroundColor: '#22C55E',
		borderColor: '#22C55E',
	},
	statusOptionText: {
		fontSize: 12,
		color: colors.orangeShade5,
		fontWeight: '500',
	},
	statusOptionTextSelected: {
		color: '#FFF',
	},
	completionInput: {
		backgroundColor: colors.ivory2,
		borderRadius: 8,
		padding: spacing.small,
		borderWidth: 1,
		borderColor: colors.ivory3,
		fontSize: 14,
		color: colors.orangeShade7,
	},
	completionTextArea: {
		minHeight: 70,
		textAlignVertical: 'top',
	},
	completionModalActions: {
		flexDirection: 'row',
		gap: 10,
		marginTop: spacing.large,
	},
	completionCancelBtn: {
		flex: 1,
		paddingVertical: 14,
		borderRadius: 8,
		alignItems: 'center',
		backgroundColor: colors.ivory2,
		borderWidth: 1,
		borderColor: colors.ivory3,
	},
	completionCancelBtnText: {
		color: colors.orangeShade6,
		fontWeight: '600',
		fontSize: 14,
	},
	completionSubmitBtn: {
		flex: 1.5,
		flexDirection: 'row',
		paddingVertical: 14,
		borderRadius: 8,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#22C55E',
		gap: 6,
	},
	completionSubmitBtnText: {
		color: '#FFF',
		fontWeight: '700',
		fontSize: 14,
	},
	// Proof image styles
	proofHint: {
		fontSize: 12,
		color: colors.orangeShade4,
		marginBottom: 10,
	},
	proofButtonsRow: {
		flexDirection: 'row',
		gap: 10,
		marginBottom: spacing.small,
	},
	proofButton: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: 14,
		backgroundColor: colors.ivory2,
		borderRadius: 10,
		borderWidth: 1,
		borderColor: colors.primary + '40',
		borderStyle: 'dashed',
		gap: 8,
	},
	proofButtonText: {
		fontSize: 13,
		fontWeight: '600',
		color: colors.primary,
	},
	proofImageContainer: {
		position: 'relative',
		marginBottom: spacing.small,
	},
	proofImagePreview: {
		width: '100%',
		height: 180,
		borderRadius: 10,
		resizeMode: 'cover',
	},
	removeImageBtn: {
		position: 'absolute',
		top: 8,
		right: 8,
		backgroundColor: '#FFF',
		borderRadius: 14,
	},
	pendingApprovalNote: {
		fontSize: 12,
		color: '#F59E0B',
		textAlign: 'center',
		marginTop: spacing.medium,
		paddingTop: spacing.small,
		borderTopWidth: 1,
		borderTopColor: colors.ivory3,
	},
});
